all:
  # For now localhost is my "bastion server" to run ansible-playbook commands from
  hosts:
    localhost:
      ansible_connection: local

  children:
    proxmoxs: # Group for Proxmox server
      hosts:
        proxmox-nuc:
          ansible_host: 192.168.1.10
    vaults:
      hosts:
        vault-debian:
          ansible_host: 192.168.1.23
