- name: Show current user in local
  hosts: localhost
  tasks:
    - name: Run whoami command and register output
      ansible.builtin.command: whoami
      register: whoami_result

    - name: Display whoami result
      ansible.builtin.debug:
        msg: "The current user is {{ whoami_result.stdout }}"
