---
- name: Add host in /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ ansible_all_ipv4_addresses[0] }}"
    owner: root
    group: root
    mode: "0644"
    state: present
    line: "{{ ansible_all_ipv4_addresses[0] }} {{ ansible_hostname }}.{{ domainname }} {{ ansible_hostname }}"
- name: Remove loopback address from /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1.*"
    owner: root
    group: root
    mode: "0644"
    state: absent
- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - gpg
    state: present
- name: Add Proxmox VE repository
  become: true
  ansible.builtin.deb822_repository:
    name: proxmox
    types: deb
    uris: http://download.proxmox.com/debian/pve
    suites: "{{ ansible_distribution_release }}"
    components: pve-no-subscription
    architectures: amd64
    signed_by: https://enterprise.proxmox.com/debian/proxmox-archive-keyring-{{ ansible_distribution_release }}.gpg
  notify:
    - Update apt cache
# Force apt cache update before installing proxmox packages
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Remove repo
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.sources
    state: absent
- name: Set IPV4
  become: true
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/proxmox.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    - { name: net.ipv4.ip_forward, value: 1 }
- name: Remove dual-boot package os-prober
  become: true
  ansible.builtin.package:
    name:
      - os-prober
    state: absent
- name: Install Proxmox packages & tools
  become: true
  ansible.builtin.package:
    name:
      - proxmox-ve
      - ksm-control-daemon
      - locales-all
      - open-iscsi
      - chrony
      - libguestfs-tools
    state: present
- name: Remove debian kernel
  become: true
  ansible.builtin.package:
    name: "linux-image-6.1*"
    state: absent
- name: Copy interface
  become: true
  ansible.builtin.copy:
    dest: /etc/network/interfaces
    content: "{{ proxmox_interfaces }}"
    owner: root
    group: root
    mode: "0644"
- name: Reboot server
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 120
- name: Wait for Proxmox to come back online
  ansible.builtin.wait_for:
    port: 22
    host: "{{ ansible_host }}"
    timeout: 330
- name: Try to curl Proxmox web GUI
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:8006"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: no
  register: result
  # until: result.status == 200
  # retries: 5
  # delay: 15
- name: Print Proxmox web GUI result
  ansible.builtin.debug:
    msg: "{{ result.content }}"
