galaxy_info:
  author: harold
  role_name: users
  namespace: harold
  description: Install proxmox on top of a debian server
  company: none
  license: MLP2
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - Trixie
  galaxy_tags:
    - proxmox
    - debian
dependencies: []
